import React from 'react';
import servicesData from "../../data/Service";
import Image from 'next/image';
import Link from 'next/link';
import { FaAngleDoubleRight } from 'react-icons/fa';
export async function generateMetadata() {
    return {
      title: 'Service Details Page',
      description: "Generated by create Service Page",
    }
  }
export async function generateStaticParams() {
    const contenId = servicesData.map((conten) => ({ id: conten.id.toString() }));
    return contenId;
}

export default function ServiceDetailsPage({ params }) {
    const contenItem = servicesData.find((item) => item.id == params.id);

    if (!contenItem) {
        return <div>Content not found</div>;
    }

    return (
      <div>
          <div>
        <h2 className="sm:text-[28px] tracking-widest px-4 sm:px-16 bg-[#EEF7FF] uppercase font-bold border-t-2 mt-16 border-b-2 mb-5 py-4 sm:py-8">
          Modern Warehouse
        </h2>
        <div className="border-b-2 flex items-center gap-3 px-4 pb-4 sm:px-16">
          <p className="text-sm text-gray-600 hover:text-[#4ae2fa] hover:underline cursor-pointer">
            Airon solution Ltd.
          </p>
          <FaAngleDoubleRight />
          <Link href='/our-service'>
            <p className="text-sm text-gray-600 capitalize hover:text-[#4ae2fa] hover:underline cursor-pointer">
              Our Service
            </p>
          </Link>
          <FaAngleDoubleRight />
          <p className="text-sm text-gray-600 capitalize">Modern Warehouse</p>
        </div>
      </div>
      <div className="px-4 sm:px-20 my-10">
        <Image
          className="w-full "
          src="/img/modern_warehouse_banner_pic.jpg"
          alt="Modern Warehouse image"
          width={700}
          height={500}
        />
      </div>
      <div>
        {/* <ImageFilter /> */}
      </div>
      </div>
    );
}
